apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    vendor: crunchydata
  name: crunchy-postgres-exporter
  namespace: postgres-operator
spec:
  namespaceSelector:
    matchNames:
    - postgres-operator
  podMetricsEndpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: exporter
    relabelings:
    - action: keep
      regex: "true"
      separator: ""
      sourceLabels:
      - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_crunchy_postgres_exporter
      - __meta_kubernetes_pod_label_crunchy_postgres_exporter
    - action: drop
      regex: "5432"
      sourceLabels:
      - __meta_kubernetes_pod_container_port_number
    - action: drop
      regex: "8009"
      sourceLabels:
      - __meta_kubernetes_pod_container_port_number
    - action: drop
      regex: "2022"
      sourceLabels:
      - __meta_kubernetes_pod_container_port_number
    - action: drop
      regex: "10000"
      sourceLabels:
      - __meta_kubernetes_pod_container_port_number
    - action: drop
      regex: ^$
      sourceLabels:
      - __meta_kubernetes_pod_container_port_number
    - action: replace
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: kubernetes_namespace
    - sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod
    - replacement: $1$2
      separator: ':'
      sourceLabels:
      - __meta_kubernetes_namespace
      - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_cluster
      targetLabel: pg_cluster
    - replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_ip
      targetLabel: ip
    - replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance
      targetLabel: deployment
    - replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role
      targetLabel: role
    - replacement: $1
      sourceLabels:
      - dbname
      targetLabel: dbname
    - replacement: $1
      sourceLabels:
      - relname
      targetLabel: relname
    - replacement: $1
      sourceLabels:
      - schemaname
      targetLabel: schemaname
    - replacement: pg
      targetLabel: exp_type
  podTargetLabels:
  - deployment
  - role
  - pg_cluster
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
