###
#
# Copyright © 2017-2022 Crunchy Data Solutions, Inc. All Rights Reserved.
#
###

# Based on upstream example file found here: https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml

inhibitRules:
# Apply inhibition of warning if the alertname for the same system and service is already critical
- sourceMatch:
  - name: 'severity'
    value: 'critical'
  targetMatch:
  - name: 'severity'
    value: 'warning'
  equal: ['alertname', 'job', 'service']

receivers:
- name: 'default-receiver'
  emailConfigs:
  # https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.EmailConfig
  - to: 'example@crunchydata.com'
    sendResolved: true
    smarthost: 'localhost: 25'
    requireTLS: false
    from: 'Alertmanager <abc@yahoo.com>'


## Examples of alternative alert receivers. See documentation for more info on how to configure these fully
#- name: 'pagerduty-dba'
#  pagerduty_configs:
#      - service_key: <RANDOMKEYSTUFF>

#- name: 'pagerduty-sre'
#  pagerduty_configs:
#      - service_key: <RANDOMKEYSTUFF>

#- name: 'dba-team'
#  email_configs:
#  - to: 'example-dba-team@crunchydata.com'
#    send_resolved: true

#- name: 'sre-team'
#  email_configs:
#  - to: 'example-sre-team@crunchydata.com'
#    send_resolved: true

route:
    receiver: default-receiver
    groupBy: [severity, service, job, alertname]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 24h

## Example routes to show how to route outgoing alerts based on the content of that alert
#    routes:
#    - match_re:
#        service: ^(postgresql|mysql|oracle)$
#      receiver: dba-team
#      # sub route to send critical dba alerts to pagerduty
#      routes:
#      - match:
#          severity: critical
#        receiver: pagerduty-dba
#
#    - match:
#        service: system
#      receiver: sre-team
#      # sub route to send critical sre alerts to pagerduty
#      routes:
#      - match:
#          severity: critical
#        receiver: pagerduty-sre
